package view;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import dao.object.AdminDAO;
import model.Admin;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class LoginFrm extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form DemoFrm
	 */

	public LoginFrm() {
		initComponents();
		this.setTitle("Caro Game");
		this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
	}

	public LoginFrm(String taiKhoan, String matKhau) {
		initComponents();
		jPasswordField1.setText(matKhau);
		jTextField1.setText(taiKhoan);
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
	}

	public void showError(String message) {
		JOptionPane.showMessageDialog(rootPane, message);
	}

	public void log(String message) {
		JOptionPane.showMessageDialog(rootPane, "ID của server thread là:" + message);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	public void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Tài khoản");

		jLabel2.setText("Mật khẩu");

		jButton1.setText("Đăng Nhập");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jPanel1.setBackground(new java.awt.Color(102, 102, 102));

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Đăng Nhập cho Admin");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(61)
					.addComponent(jLabel3)
					.addContainerGap(67, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap(20, Short.MAX_VALUE)
					.addComponent(jLabel3)
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(43)
						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jTextField1, GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
								.addComponent(jPasswordField1))
						.addContainerGap(39, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(109).addComponent(jButton1).addContainerGap(118,
						Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jButton1)
				.addContainerGap(55, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		try {
			String taiKhoan = jTextField1.getText();
			if (taiKhoan.isEmpty())
				throw new Exception("Vui lòng nhập tên tài khoản");
			String matKhau = String.copyValueOf(jPasswordField1.getPassword());
			if (matKhau.isEmpty())
				throw new Exception("Vui lòng nhập mật khẩu");
			AdminView.closeAllViews();
			AdminView.openView(AdminView.View.GAMENOTICE, "Đăng nhập", "Đang xác thực thông tin đăng nhập");

			if (!taiKhoan.isEmpty() && !matKhau.isEmpty()) {
				Admin ad = new Admin(1, taiKhoan, matKhau, taiKhoan);
				AdminDAO adDAO = new AdminDAO();

				if (adDAO.verifyAdmin(ad) != null) {
					System.out.println("Đăng nhập thành công");
					AdminView.closeAllViews();
					AdminView view = new AdminView(true);
				} else {
					AdminView.closeView(AdminView.View.GAMENOTICE);
					AdminView.openView(AdminView.View.LOGIN, taiKhoan, matKhau);
					AdminView.loginFrm.showError("Tài khoản hoặc mật khẩu không chính xác");
				}

			}

//            Admin.socketHandle.write("client-verify,"+taiKhoan+","+matKhau);            
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(rootPane, ex.getMessage());
			System.out.println("cant");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;

}
